# Site settings
title: Japan
client:
  name: Visit Japan
  link: "https://www.japan.travel/de/de/"
  link2: "https://www.geoplan-reisen.de/"

core-se-link: https://www.secretescapes.de/aktuelle-angebote # DE
description: >
  Japan ist ein Füllhorn an Eindrücken. Es ist beeindruckend, wieviele Seiten das kompakte und spirituelle Land offenbart: Samurais und Geishas, Onsen und Ramen, Kyoto und die Berge Kyushus.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/2020/japan" # the subpath of the site, including territory and year
img:     "/de/2020/japan/_assets/img"
css:     "/de/2020/japan/_assets/css"
js:      "/de/2020/japan/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
